'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ea=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(){this.o=!1;this.l=null;this.h=void 0;this.g=1;this.v=this.i=0;this.m=null}function na(a){if(a.o)throw new TypeError("Generator is already running");a.o=!0}ma.prototype.u=function(a){this.h=a};function oa(a,b){a.m={W:b,isException:!0};a.g=a.i||a.v}
ma.prototype.return=function(a){this.m={return:a};this.g=this.v};function r(a,b,c){a.g=c;return{value:b}}function pa(a,b){a.g=b;a.i=0}function qa(a){a.i=0;var b=a.m.W;a.m=null;return b}function ra(a){this.g=new ma;this.h=a}function sa(a,b){na(a.g);var c=a.g.l;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ua(a)}
function ta(a,b,c,d){try{var e=b.call(a.g.l,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.o=!1,e;var f=e.value}catch(g){return a.g.l=null,oa(a.g,g),ua(a)}a.g.l=null;d.call(a.g,f);return ua(a)}
function ua(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.o=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,oa(a.g,c)}a.g.o=!1;if(a.g.m){b=a.g.m;a.g.m=null;if(b.isException)throw b.W;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){na(a.g);a.g.l?b=ta(a,a.g.l.next,b,a.g.u):(a.g.u(b),b=ua(a));return b};this.throw=function(b){na(a.g);a.g.l?b=ta(a,a.g.l["throw"],b,a.g.u):(oa(a.g,b),b=ua(a));return b};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return wa(new va(new ra(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return xa(la(this))}});return a});function xa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.l(m)}}}this.g=null};c.prototype.l=function(g){this.i(function(){throw g;})};b.prototype.l=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.C),reject:g(this.m)}};b.prototype.C=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.B(g):this.o(g)}};
b.prototype.B=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.H(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.F();this.D()};b.prototype.F=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.D=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.G=function(g){var h=this.l();g.K(h.resolve,h.reject)};b.prototype.H=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(x,z){return typeof x=="function"?function(G){try{m(x(G))}catch(C){n(C)}}:z}var m,n,w=new b(function(x,z){m=x;n=z});this.K(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.K=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).K(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(C){x[G]=C;z--;z==0&&m(x)}}var x=[],z=0;do x.push(void 0),z++,d(k.value).K(w(x.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ya=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||ya});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return xa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Aa=this||self;function Ba(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=Aa,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ca(a){return a};var Da=Ba(610401301,!1),Ea=Ba(748402147,!0);function Fa(){return typeof BigInt==="function"};var Ga=typeof Aa.BigInt==="function"&&typeof Aa.BigInt(0)==="bigint";var Ha=Number.MIN_SAFE_INTEGER.toString(),Ia=Ga?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ja=Number.MAX_SAFE_INTEGER.toString(),Ka=Ga?BigInt(Number.MAX_SAFE_INTEGER):void 0;function La(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ma=typeof Uint8Array.prototype.slice==="function",v=0,y=0,Na;function Oa(a){var b=a>>>0;v=b;y=(a-b)/4294967296>>>0}function Pa(a){if(a<0){Oa(-a);var b=q(Qa(v,y));a=b.next().value;b=b.next().value;v=a>>>0;y=b>>>0}else Oa(a)}function Ra(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;v=b.getUint32(0,!0)}function Sa(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function Ta(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Ua(a,b)}function Va(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=Ta(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}
function Ua(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Fa()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+Wa(c)+Wa(a));return c}function Wa(a){a=String(a);return"0000000".slice(a.length)+a}
function Xa(a){if(a.length<16)Pa(Number(a));else if(Fa())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,v=v*1E6+d,v>=4294967296&&(y+=Math.trunc(v/4294967296),y>>>=0,v>>>=0);b&&(b=q(Qa(v,y)),a=b.next().value,b=b.next().value,v=a,y=b)}}function Qa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function Ya(a,b){this.h=a>>>0;this.g=b>>>0}function Za(a){return a.h===0?new Ya(0,1+~a.g):new Ya(~a.h+1,~a.g)}function $a(a){a=BigInt.asUintN(64,a);return new Ya(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function ab(a){if(!a)return bb||(bb=new Ya(0,0));if(!/^\d+$/.test(a))return null;Xa(a);return new Ya(v,y)}var bb;function cb(a,b){this.h=a>>>0;this.g=b>>>0}function db(a){a=BigInt.asUintN(64,a);return new cb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function eb(a){if(!a)return fb||(fb=new cb(0,0));if(!/^-?\d+$/.test(a))return null;Xa(a);return new cb(v,y)}var fb;function gb(){throw Error("Invalid UTF8");}function hb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var ib=void 0,jb,kb=typeof TextDecoder!=="undefined",lb,mb=typeof String.prototype.isWellFormed==="function",nb=typeof TextEncoder!=="undefined";
function ob(a){var b=!1;b=b===void 0?!1:b;if(nb){if(b&&(mb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(lb||(lb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function pb(a){Aa.setTimeout(function(){throw a;},0)};function qb(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}var rb,sb=Aa.navigator;rb=sb?sb.userAgentData||null:null;var tb={},ub=null;function vb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;wb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function wb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=ub[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}xb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function xb(){if(!ub){ub={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));tb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];ub[f]===void 0&&(ub[f]=e)}}}};var yb=typeof Uint8Array!=="undefined",zb=!(Da&&rb&&rb.brands.length>0?0:qb().indexOf("Trident")!=-1||qb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Ab=/[-_.]/g,Bb={"-":"+",_:"/",".":"="};function Cb(a){return Bb[a]||""}function Db(a){if(!zb)return vb(a);a=Ab.test(a)?a.replace(Ab,Cb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Eb={};function Fb(a,b){Gb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Hb(){return Ib||(Ib=new Fb(null,Eb))}function Jb(a){Gb(Eb);var b=a.g;b=b==null||yb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Db(b):null;return b==null?b:a.g=b}var Ib;function Gb(a){if(a!==Eb)throw Error("illegal external caller");};function Kb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Lb(a,b){if(typeof a==="string")return new Kb(Db(a),b);if(Array.isArray(a))return new Kb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Kb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Kb(a,!1);if(a.constructor===Fb)return b=Jb(a)||new Uint8Array(0),new Kb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Kb(a,!1);throw Error();};function Mb(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.init(a,b,c,d)}Mb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.J===void 0?!1:e.J;e=e.L===void 0?!1:e.L;this.J=d;this.L=e;a&&(a=Lb(a,this.L),this.h=a.buffer,this.m=a.g,this.l=b||0,this.i=c!==void 0?this.l+c:this.h.length,this.g=this.l)};Mb.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.J=!1};
function Ob(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Pb(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function Pb(a,b){a.g=b;if(b>a.i)throw Error();}
function Qb(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();Pb(a,c);return e}function Rb(a){return Qb(a)>>>0}function Sb(a){a=Rb(a);return a>>>1^-(a&1)}function Tb(a){return Ob(a,Va)}function Ub(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Pb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function Vb(a){var b=Ub(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function Wb(a){var b=Ub(a),c=Ub(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function Xb(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Pb(a,c),!!(b&127)}throw Error();}
function Yb(a){return Qb(a)}function Zb(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function $b(a,b){if(b==0)return Hb();var c=Zb(a,b);a.J&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ma?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Hb():new Fb(c,Eb)}var ac=[],bc=void 0;function cc(){this.g=[]}cc.prototype.length=function(){return this.g.length};cc.prototype.end=function(){var a=this.g;this.g=[];return a};function dc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function ec(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function fc(a,b){if(b>=0)ec(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function A(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function hc(a,b,c,d){if(ac.length){var e=ac.pop();e.init(a,b,c,d);a=e}else a=new Mb(a,b,c,d);this.g=a;this.l=this.g.g;this.h=this.i=-1;this.setOptions(d)}hc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.T=a.T===void 0?!1:a.T};function ic(a,b,c,d){if(jc.length){var e=jc.pop();e.setOptions(d);e.g.init(a,b,c,d);return e}return new hc(a,b,c,d)}function kc(a){a.g.clear();a.i=-1;a.h=-1;jc.length<100&&jc.push(a)}
function lc(a){var b=a.g;if(b.g==b.i)return!1;a.l=a.g.g;var c=Rb(a.g);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.h=c;return!0}function mc(a){switch(a.h){case 0:a.h!=0?mc(a):Xb(a.g);break;case 1:a=a.g;Pb(a,a.g+8);break;case 2:if(a.h!=2)mc(a);else{var b=Rb(a.g);a=a.g;Pb(a,a.g+b)}break;case 5:a=a.g;Pb(a,a.g+4);break;case 3:b=a.i;do{if(!lc(a))throw Error();if(a.h==4){if(a.i!=b)throw Error();break}mc(a)}while(1);break;default:throw Error();}}
function nc(a,b,c){var d=a.g.i,e=Rb(a.g);e=a.g.g+e;var f=e-d;f<=0&&(a.g.i=e,c(b,a,void 0,void 0,void 0),f=e-a.g.g);if(f)throw Error();a.g.g=e;a.g.i=d;return b}
function oc(a){var b=Rb(a.g);a=a.g;var c=Zb(a,b);a=a.h;if(kb){var d=a,e;(e=jb)||(e=jb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(ib===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),ib=!0}catch(n){ib=!1}}!ib&&(jb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?gb():(k=a[f++],h<194||(k&192)!==128?(f--,gb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?gb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,gb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?gb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,gb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):gb(),c.length>=8192&&(g=hb(g,c),c.length=0);f=hb(g,c)}return f}function pc(a){var b=Rb(a.g);return $b(a.g,b)}
function qc(a,b,c){var d=Rb(a.g);for(d=a.g.g+d;a.g.g<d;)c.push(b(a.g))}var jc=[];function rc(){this.i=[];this.h=0;this.g=new cc}function sc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function tc(a,b){B(a,b,2);b=a.g.end();sc(a,b);b.push(a.h);return b}function uc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){ec(a.g,b*8+c)}function vc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),fc(a.g,c))}function wc(a,b,c){B(a,b,2);ec(a.g,c.length);sc(a,a.g.end());sc(a,c)}
function xc(a,b,c,d){c!=null&&(b=tc(a,b),d(c,a),uc(a,b))}function yc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?ab(a.substring(1)):ab(a)}};var zc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Ac(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Bc=Ac("jas",void 0,!0),Cc=Ac(void 0,"1oa"),Dc=Ac(void 0,Symbol()),Ec=Ac(void 0,"0ubs"),Fc=Ac(void 0,"0ubsb"),Gc=Ac(void 0,"0actk"),Hc=Ac("m_m","ba",!0);var Ic={aa:{value:0,configurable:!0,writable:!0,enumerable:!1}},Jc=Object.defineProperties,D=zc?Bc:"aa",Kc,Lc=[];E(Lc,7);Kc=Object.freeze(Lc);function Mc(a,b){zc||D in a||Jc(a,Ic);a[D]|=b}function E(a,b){zc||D in a||Jc(a,Ic);a[D]=b}function Nc(a){Mc(a,8192);return a};var Oc={};function Pc(a,b){return b===void 0?a.g!==Qc&&!!(2&(a.j[D]|0)):!!(2&b)&&a.g!==Qc}var Qc={};function Rc(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var Sc={};function Tc(a){return a&128?Sc:void 0};function Uc(a){return a};var Vc=void 0;function Wc(a,b){if(a!=null){var c;var d=(c=Vc)!=null?c:Vc={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",pb(a))}};function Xc(a){return Array.prototype.slice.call(a)};var Yc=typeof BigInt==="function"?BigInt.asIntN:void 0,Zc=typeof BigInt==="function"?BigInt.asUintN:void 0,$c=Number.isSafeInteger,ad=Number.isFinite,bd=Math.trunc;function cd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function dd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function id(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var jd=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function kd(a){switch(typeof a){case "bigint":return!0;case "number":return ad(a);case "string":return jd.test(a);default:return!1}}function ld(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return ad(a)?a|0:void 0}
function md(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return ad(a)?a>>>0:void 0}
function nd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(Yc(64,a));if(kd(a)){if(b==="string")return b=bd(Number(a)),$c(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(Xa(a),a=v,b=y,b&2147483648?Fa()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Qa(a,b)),a=b.next().value,b=b.next().value,a="-"+Ua(a,b)):a=Ua(a,b))),a;if(b==="number")return a=bd(a),$c(a)||
(Pa(a),a=Va(v,y)),a}}function od(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(Zc(64,a));if(kd(a)){if(b==="string")return b=bd(Number(a)),$c(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(Xa(a),a=Ua(v,y))),a;if(b==="number")return a=bd(a),a>=0&&$c(a)||(Pa(a),a=Ta(v,y)),a}}function pd(a){if(a==null||typeof a=="string"||a instanceof Fb)return a}
function qd(a){if(a!=null&&typeof a!=="string")throw Error();return a}function rd(a){return a==null||typeof a==="string"?a:void 0};function sd(a){var b=Ca(Dc);return b?a[b]:void 0}function td(){}function ud(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function vd(a){var b=new td;ud(a,function(c,d,e){b[d]=Xc(e)});b.g=a.g;return b}function wd(a,b){b<100||Wc(Ec,1)};function xd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ca(Dc),g;!e&&zc&&f&&(g=a[f])&&ud(g,wd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var x;g=((x=yd)!=null?x:Uc)(g-n,n,a,w,void 0)+n}}b=void 0;for(x=0;x<h;x++){var z=a[x];if(z!=null&&(z=c(z,d))!=null)if(m&&x>=g){var G=x-n,C=void 0;((C=b)!=null?C:b={})[G]=z}else f[x]=z}if(w)for(var T in w)h=w[T],h!=
null&&(h=c(h,d))!=null&&(x=+T,z=void 0,m&&!Number.isNaN(x)&&(z=x+n)<g?f[z]=h:(x=void 0,((x=b)!=null?x:b={})[T]=h));b&&(k?f.push(b):f[g]=b);e&&Ca(Dc)&&(a=sd(a))&&a instanceof td&&(f[Dc]=vd(a));return f}
function zd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ga?a>=Ia&&a<=Ka:a[0]==="-"?La(a,Ha):La(a,Ja))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[D]|0;return a.length===0&&b&1?void 0:xd(a,b,zd)}if(a!=null&&a[Hc]===Oc)return Ad(a);if(a instanceof Fb){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(zb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=
String.fromCharCode.apply(null,d?b.subarray(d):b);b=btoa(c)}else{c===void 0&&(c=0);xb();c=tb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var yd;function Ad(a){a=a.j;return xd(a,a[D]|0,zd)};var Bd,Cd;function Dd(a){switch(typeof a){case "boolean":return Bd||(Bd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Cd||(Cd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Ed(a,b){return F(a,b[0],b[1])}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[D]|0;if(Ea&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Fd();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function Fd(){if(Ea)throw Error("carr");Wc(Gc,5)};function Gd(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[D]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Hd(a,c,!1,b&&!(c&16)):(Mc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Hc]===Oc)return b=a.j,c=b[D]|0,Pc(a,c)?a:Id(a,b,c)?Jd(a,b):Hd(b,c);if(a instanceof Fb)return a}function Jd(a,b,c){a=new a.constructor(b);c&&(a.g=Qc);a.h=Qc;return a}function Hd(a,b,c,d){d!=null||(d=!!(34&b));a=xd(a,b,Gd,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Kd(a){if(a.g!==Qc)return!1;var b=a.j;b=Hd(b,b[D]|0);Mc(b,2048);a.j=b;a.g=void 0;a.h=void 0;return!0}function Ld(a){if(!Kd(a)&&Pc(a,a.j[D]|0))throw Error();}function Md(a,b){b===void 0&&(b=a[D]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Id(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Qc,!0):!1};function Nd(a,b,c){a=Od(a.j,b,void 0,c);if(a!==null)return a}function Od(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function Pd(a,b,c){Ld(a);var d=a.j;H(d,d[D]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[D]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function Qd(a,b){return Rd(a,a[D]|0,b)}function Sd(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function Td(a){return a==null?a:typeof a==="string"?a?new Fb(a,Eb):Hb():a.constructor===Fb?a:yb&&a!=null&&a instanceof Uint8Array?a.length?new Fb(new Uint8Array(a),Eb):Hb():void 0}function Rd(a,b,c){if(b&2)throw Error();var d=Tc(b);var e=Od(a,c,d);e=Array.isArray(e)?e:Kc;var f=e===Kc?7:e[D]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||Sd(g)||16&g)g===f||Sd(g)||E(e,g),e=Xc(e),f=0,g=Ud(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function Vd(a,b,c,d){Ld(a);var e=a.j,f=e[D]|0;if(d==null){var g=Wd(e);if(Xd(g,e,f,c)===b)g.set(c,0);else return a}else f=Yd(e,f,c,b);H(e,f,b,d);return a}function Zd(a,b,c,d){var e=a[D]|0,f=Tc(e);e=Yd(a,e,c,b,f);H(a,e,b,d,f)}function Wd(a){if(zc){var b;return(b=a[Cc])!=null?b:a[Cc]=new Map}if(Cc in a)return a[Cc];b=new Map;Object.defineProperty(a,Cc,{value:b});return b}function Yd(a,b,c,d,e){var f=Wd(a),g=Xd(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function Xd(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Od(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function $d(a,b,c){var d=a[D]|0,e=Tc(d),f=Od(a,c,e);if(f!=null&&f[Hc]===Oc){if(!Pc(f))return Kd(f),f.j;var g=f.j}else Array.isArray(f)&&(g=f);if(g){var h=g[D]|0;h&2&&(g=Hd(g,h))}g=Ed(g,b);g!==f&&H(a,d,c,g,e);return g}
function ae(a,b){var c=be,d=!1,e=Od(a,4,void 0,function(f){if(f!=null&&f[Hc]===Oc)var g=f;else if(Array.isArray(f)){g=f[D]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Pc(e)&&Md(a,b),e}function ce(a){var b=a.j,c=b[D]|0,d=ae(b,c);if(d==null)return d;c=b[D]|0;if(!Pc(a,c)){var e=d;var f=e.j,g=f[D]|0;e=Pc(e,g)?Id(e,f,g)?Jd(e,f,!0):new e.constructor(Hd(f,g,!1)):e;e!==d&&(Kd(a)&&(b=a.j,c=b[D]|0),d=e,c=H(b,c,4,d),Md(b,c))}return d}
function de(a){a==null&&(a=void 0);return a}function ee(a,b,c){c=de(c);Pd(a,b,c);c&&!Pc(c)&&Md(a.j);return a}function fe(a,b){Ld(a);var c=a.j,d=c[D]|0;if(b==null)return H(c,d,1),a;for(var e=b===Kc?7:b[D]|0,f=e,g=Sd(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Pc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=Xc(b),f=0,e=Ud(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||Md(c,d);return a}function Ud(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.j=F(a,b,c,2048)}I.prototype.toJSON=function(){var a=Ad(this);return a};I.prototype[Hc]=Oc;I.prototype.toString=function(){return this.j.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var ge=J(),he=J(),ie=J(),je=J(),ke=J(),le=J(),me=J(),ne=J(),oe=J(),pe=J();function qe(a,b,c){this.g=a;this.h=b;a=Ca(ge);this.i=!!a&&c===a||!1}function re(a,b){var c=c===void 0?ge:c;return new qe(a,b,c)}function se(a,b,c,d,e){xc(a,c,te(b,d),e)}var ue=re(function(a,b,c,d,e){if(a.h!==2)return!1;nc(a,$d(b,d,c),e);return!0},se),ve=re(function(a,b,c,d,e){if(a.h!==2)return!1;nc(a,$d(b,d,c),e);return!0},se),we=Symbol(),xe=Symbol(),ye=Symbol(),ze=Symbol(),Ae=Symbol(),Be,Ce;
function De(a,b,c,d){var e=d[a];if(e)return e;e={};e.Z=d;e.I=Dd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.U=f,f=d[++g],typeof f==="function"&&(e.X=!0,Be!=null||(Be=f),Ce!=null||(Ce=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof qe)var n=f;else n=ue,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var x=h[k];m?c(e,k,n,m,x):b(e,k,n,x)}}return d[a]=e}function Ee(a){return Array.isArray(a)?a[0]instanceof qe?a:[ve,a]:[a,void 0]}function te(a,b){if(a instanceof I)return a.j;if(Array.isArray(a))return Ed(a,b)};function Fe(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Ge(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=De(xe,Fe,Ge,d).I),g||(g=He(d)),e)}}
function He(a){var b=a[ye];if(b!=null)return b;var c=De(xe,Fe,Ge,a);b=c.X?function(d,e){return Be(d,e,c)}:function(d,e){for(;lc(e)&&e.h!=4;){var f=e.i,g=c[f];if(g==null){var h=c.U;h&&(h=h[f])&&(h=Ie(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.l;mc(h);if(h.T)var k=void 0;else{var m=h.g.g-g;h.g.g=g;k=$b(h.g,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Dc])!=null?m:n[Dc]=new td)[f])!=null?g:h[f]=[]).push(k)}}if(d=sd(d))d.g=c.Z[Ae];return!0};a[ye]=b;a[Ae]=Je.bind(a);return b}
function Je(a,b,c,d){var e=this[xe],f=this[ye],g=Ed(void 0,e.I),h=sd(a);if(h){var k=!1,m=e.U;if(m){e=function(G,C,T){if(T.length!==0)if(m[C])for(G=q(T),C=G.next();!C.done;C=G.next()){C=ic(C.value);try{k=!0,f(g,C)}finally{kc(C)}}else d==null||d(a,C,T)};if(b==null)ud(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[D]|0;if(w&2&&w&2048&&(c==null||!c.da))throw Error();var x=Tc(w),z=function(G,C){if(Od(a,G,x)!=null)switch(c==null?void 0:c.ca){case 1:return;default:throw Error();}C!=null&&(w=
H(a,w,G,C,x));delete h[G]};b==null?Rc(g,g[D]|0,function(G,C){z(G,C)}):z(b,Od(g,b,x))}}}}function Ie(a){a=Ee(a);var b=a[0].g;if(a=a[1]){var c=He(a),d=De(xe,Fe,Ge,a).I;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ke(a,b,c){a[b]=c.h}function Le(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=De(we,Ke,Le,d).I),e||(e=Me(d)))}}function Me(a){var b=a[ze];if(!b){var c=De(we,Ke,Le,a);b=function(d,e){return Ne(d,e,c)};a[ze]=b}return b}function Ne(a,b,c){Rc(a,a[D]|0,function(d,e){if(e!=null){var f=Oe(c,d);f?f(b,e,d):d<500||Wc(Fc,3)}});(a=sd(a))&&ud(a,function(d,e,f){sc(b,b.g.end());for(d=0;d<f.length;d++)sc(b,Jb(f[d])||new Uint8Array(0))})}
function Oe(a,b){var c=a[b];if(c)return c;if(c=a.U)if(c=c[b]){c=Ee(c);var d=c[0].h;if(c=c[1]){var e=Me(c),f=De(we,Ke,Le,c).I;c=a.X?Ce(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[D]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new qe(a,b,c)}function M(a,b,c){return new qe(a,b,c)}function N(a,b,c){H(a,a[D]|0,b,c,Tc(a[D]|0))}
var Pe=re(function(a,b,c,d,e){if(a.h!==2)return!1;a=nc(a,Ed([void 0,void 0],d),e);a=Xc(a);d=b[D]|0;e=Tc(d);if(d&2)throw Error();var f=Od(b,c,e);if(Array.isArray(f)){var g=f[D]|0;g&8192||E(f,g|=8192);if(g&2){f=Xc(f);for(g=0;g<f.length;g++){var h=f[g]=Xc(f[g]);if(Array.isArray(h[1])){var k=h[1];Mc(k,34);h[1]=k}}f=Nc(f);H(b,d,c,f,e)}f.push(a)}else H(b,d,c,Nc([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&xc(a,c,Ed(g,d),e)}Nc(b)}});
function Qe(a,b,c){b=dd(b);b!=null&&(B(a,c,1),a=a.g,Sa(b),A(a,v),A(a,y))}function Re(a,b,c){b=dd(b);b!=null&&(B(a,c,5),a=a.g,Ra(b),A(a,v))}function Se(a,b,c){b=nd(b);if(b!=null){switch(typeof b){case "string":eb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);dc(a,v,y);break;case "bigint":c=db(b);dc(a.g,c.h,c.g);break;default:c=eb(b),dc(a.g,c.h,c.g)}}}
function Te(a,b,c){b=od(b);if(b!=null){switch(typeof b){case "string":ab(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);dc(a,v,y);break;case "bigint":c=$a(b);dc(a.g,c.h,c.g);break;default:c=ab(b),dc(a.g,c.h,c.g)}}}function Ue(a,b,c){b=ld(b);b!=null&&b!=null&&(B(a,c,0),fc(a.g,b))}function Ve(a,b,c){b=id(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function We(a,b,c){b=rd(b);b!=null&&wc(a,c,ob(b))}function Xe(a,b,c,d,e){xc(a,c,te(b,d),e)}function Ye(a,b,c){vc(a,c,ld(b))}
function Ze(a,b,c){if(a.h!==5&&a.h!==2)return!1;b=Qd(b,c);a.h==2?qc(a,Vb,b):b.push(Vb(a.g));return!0}function $e(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Qd(b,c);a.h==2?qc(a,Qb,b):b.push(Qb(a.g));return!0}function af(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Qd(b,c);a.h==2?qc(a,Xb,b):b.push(Xb(a.g));return!0}
var bf=L(function(a,b,c){if(a.h!==1)return!1;N(b,c,Wb(a.g));return!0},Qe,ne),cf=L(function(a,b,c,d){if(a.h!==1)return!1;Zd(b,c,d,Wb(a.g));return!0},Qe,ne),O=L(function(a,b,c){if(a.h!==5)return!1;N(b,c,Vb(a.g));return!0},Re,me),df=M(Ze,function(a,b,c){b=K(dd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Ra(g),A(e,v))}},me),P=M(Ze,function(a,b,c){b=K(dd,b,!0);if(b!=null&&b.length)for(B(a,c,2),ec(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Ra(b[c]);A(d,v)}},
me),ef=L(function(a,b,c,d){if(a.h!==5)return!1;Zd(b,c,d,Vb(a.g));return!0},Re,me),ff=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Tb(a.g));return!0},Se,ke),gf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Qd(b,c);a.h==2?qc(a,Tb,b):b.push(Tb(a.g));return!0},function(a,b,c){b=K(nd,b,!1);if(b!=null&&b.length){c=tc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Pa(e);dc(f,v,y);break;case "bigint":e=db(e);dc(a.g,e.h,e.g);break;default:e=eb(e),dc(a.g,e.h,e.g)}}uc(a,
c)}},ke),hf=L(function(a,b,c,d){if(a.h!==0)return!1;Zd(b,c,d,Tb(a.g));return!0},Se,ke),jf=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Ob(a.g,Ua));return!0},Te,le),kf=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Ob(a.g,Ta));return!0},Te,le),Q=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Qb(a.g));return!0},Ue,je),lf=M($e,function(a,b,c){b=K(ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),fc(e.g,g))}},je),mf=M($e,function(a,b,c){b=K(ld,b,!0);if(b!=null&&b.length){c=
tc(a,c);for(var d=0;d<b.length;d++)fc(a.g,b[d]);uc(a,c)}},je),nf=L(function(a,b,c,d){if(a.h!==0)return!1;Zd(b,c,d,Qb(a.g));return!0},Ue,je),R=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Xb(a.g));return!0},Ve,he),of=M(af,function(a,b,c){b=K(id,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},he),pf=M(af,function(a,b,c){b=K(id,b,!0);if(b!=null&&b.length)for(B(a,c,2),ec(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},he),qf=L(function(a,b,
c,d){if(a.h!==0)return!1;Zd(b,c,d,Xb(a.g));return!0},Ve,he),S=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,oc(a));return!0},We,ie),rf=L(function(a,b,c,d){if(a.h!==2)return!1;Zd(b,c,d,oc(a));return!0},We,ie),U=M(function(a,b,c){if(a.h!==2)return!1;a=oc(a);Rd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(rd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&wc(e,f,ob(g))}},ie),V,sf=void 0;sf=sf===void 0?ge:sf;
V=new qe(function(a,b,c,d,e){if(a.h!==2)return!1;d=Ed(void 0,d);Rd(b,b[D]|0,c).push(d);nc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Xe(a,b[f],c,d,e);a=b[D]|0;a&1||E(b,a|1)}},sf);
var W=re(function(a,b,c,d,e,f){if(a.h!==2)return!1;var g=b[D]|0;Yd(b,g,f,c,Tc(g));b=$d(b,d,c);nc(a,b,e);return!0},Xe),tf=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,pc(a));return!0},function(a,b,c){b=pd(b);b!=null&&wc(a,c,Lb(b,!0).buffer)},oe),X=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Rb(a.g));return!0},function(a,b,c){b=md(b);b!=null&&b!=null&&(B(a,c,0),ec(a.g,b))},J()),Y=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Qb(a.g));return!0},Ye,pe),uf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=
Qd(b,c);a.h==2?qc(a,Yb,b):b.push(Qb(a.g));return!0},function(a,b,c){b=K(ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++)vc(a,c,b[d])},pe),vf=L(function(a,b,c,d){if(a.h!==0)return!1;Zd(b,c,d,Qb(a.g));return!0},Ye,pe),wf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Qd(b,c);a.h==2?qc(a,Sb,b):b.push(Sb(a.g));return!0},function(a,b,c){b=K(ld,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),ec(e.g,(g<<1^g>>31)>>>0))}},J()),xf=[!0,S,Q],yf=[!0,S,R],zf=[!0,S,S];function Af(a){return function(b){var c=new rc;Ne(b.j,c,De(we,Ke,Le,a));sc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Bf=[0,L(function(a,b,c){if(a.h!==1)return!1;var d=a.g;a=Ub(d);d=Ub(d);N(b,c,Ua(a,d));return!0},function(a,b,c){b=od(b);if(b!=null)switch(yc(b),B(a,c,1),a=a.g,yc(b),typeof b){case "number":b<0?(c=-b,c=Za(new Ya(c&4294967295,c/4294967296)),b=c.g,A(a,c.h),A(a,b)):(Oa(b),A(a,v),A(a,y));break;case "bigint":c=b<BigInt(0)?Za($a(-b)):$a(b);b=c.g;A(a,c.h);A(a,b);break;default:c=b.length&&b[0]==="-"?Za(ab(b.substring(1))):ab(b),b=c.g,A(a,c.h),A(a,b)}},J()),-1];var Cf=[0,L(function(a,b,c){if(a.h!==5)return!1;a=a.g;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Pb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=ld(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Df=[0,Y,-1,ff,S,Cf,-1,O,Q,Y,Bf,S,Y,-1,[0,Cf,-1],Q,kf,Bf,O,[0,1,Q,-4,bf,[0,O,-1,Q],S,O,V,[0,Y,Q],Q,-1,Y,-2,O,-1,Y,O,Y,Q,[0,3,Q,-1,4,M(function(a,b,c){if(a.h!==2)return!1;a=pc(a);Rd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(pd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&wc(e,f,Lb(g,!0).buffer)}},oe)],bf],S,uf,V,[0,Bf,V,[0,S,Y],O,Y,-1],1,V,[0,kf,-1,X],Y,Bf];var Ef=[0,ff,[0,O,S,Q,S,Q,lf,ff,S,Q,S,-1,O,Q,O],tf,[0,M(function(a,b,c){if(a.h!==1&&a.h!==2)return!1;b=Qd(b,c);if(a.h==2){c=a.g;a=Rb(a.g)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;bc===void 0&&(bc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(bc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(Wb(c))}else b.push(Wb(a.g));return!0},function(a,b,c){b=K(dd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Sa(g),A(e,v),A(e,y))}},ne),-1]];function be(a){this.j=F(a,void 0,void 0,2048)}p(be,I);function Ff(a){a=Nd(a,1,Td);return a==null?Hb():a}function Gf(a){var b=16E3;b=b===void 0?0:b;a=ld(Nd(a,2));return a!=null?a:b};function Hf(a){this.j=F(a,void 0,void 0,2048)}p(Hf,I);function If(a){this.j=F(a,void 0,void 0,2048)}p(If,I);var Jf=[0,tf,Q];var Kf=[0,[1,2,3,4],rf,vf,W,[0,S,Y],vf];var Lf=[0,S,-5,O,S,U,Y,-1,V,Kf,S,-2];var Mf=[0,Q,-3];var Nf=[0,[1,2,3,4],qf,-1,rf,-1];var Of=[0,S,-1,1,S,-1,6,U,[0,X,S,X,Q,X,-4,O,X,O,-1],R,U,-1];var Z=[0,Y,-5];var Pf=[0,[0,S,-5,R,U,Z],S,-7,R,S,U,Z];var Qf=[0,U,1,Y,-1,S];var Tf=[0,S,-2,Z,S];var Uf=[0,S,-1,R,S,U,Z];var Vf=[0,V,[0,S,-1],S,R,S];var Wf=[0,S,-2,Z];var Xf=[0,S,-3,Q,S,R,S,-1,R,S,U,Z,S,-2];var Yf=[0,R,S,-3,Q,S,R,S,U,Z];var Zf=[0,S,-3,Q,S,-3,R,S,U,Z];var $f=[0,S,Q,Y,S];var ag=[0,S,-2,Q,S,R,S,R,U,Z];var bg=[0,S,-2,R];var cg=[0,Yf,ag,Uf,S,Q,S,R,S,U,Z];var dg=[0,Yf,ff,S,Q,S,R,S,U,Z,S];var eg=[0,S,-1,R,S,U,Z,R];var fg=[0,S,Q,R];var gg=[0,S,U,S,Q,S,R,S,U,Z];var hg=[0,Q,-2,R,S,Q,S,Q,S,R,S,U,Z,R];var ig=[0,Y,-1];var jg=[0,O,-1];var kg=[0,V,[0,O,-2],O,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,jg,[0,O,-1],[0,V,jg,O,Y],[0,V,jg,Y]],O];var lg=[0,O,-2];var mg=[-11,{},Mf,S,[0,pf,mf,P,U,V,[0,P],[0,P]],P,S,-1,[0,lg],S,[0,P,-1,V,[0,Y,Q]],-1];var ng=[0,Mf,[0,R,O,P,-1],Q,[0,P]];var og=[0,Y,[0,lf,gf]];var pg=[0,Y,[0,lf,U]];var qg=[0,Q,-1,Y,Q];var rg=[0,P,mf];var sg=[0,P,mf,S];var tg=[0,[0,jf,Y,R]];var ug=[0,Q,-2,S];var vg=[0,Y];var xg=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],rf,S,W,Uf,W,eg,W,Yf,W,ag,W,hg,W,cg,W,Xf,W,Pf,W,gg,W,dg,W,Zf,W,Vf,rf,-1,V,bg,rf,-1,kg,ef,[0,R,-1,Y,ig,R,-1,O,R,U,qg,Y,-1],Df,R,W,[0,S,-1],V,[0,S,-1],[0,U,R],Z,Y,vg,R,W,fg,S,U,S,W,Wf,W,Tf,S,-1,R,W,$f,R,ug,S],V,[0,S,V,[0,S,-1,Y],V,[0,S,-1],S,Y,[0,Y,-3],U,R,S],4,vg,O,R,function(){return wg},S,tg,R,[0,R,-1]],wg=[0,V,function(){return xg},-1];var yg=function(a,b){return function(c,d){var e={L:!0};d&&Object.assign(e,d);c=ic(c,void 0,void 0,e);try{var f=new a,g=f.j;He(b)(g,c);var h=f}finally{kc(c)}return h}}(If,[0,Y,2,Jf,Y,[-500,{},kf,S,xg,-1,1,[0,Y,Q,-1,O],[0,S,-5,Q,S,1,R,-1,S,Y,V,Lf,S],ff,-2,89,[-5,{},V,[-75,{},Mf,X,-1,S,Y,S,-2,R,O,Y,S,R,-1,5,Uf,eg,S,Yf,ag,hg,cg,Yf,Xf,Pf,gg,dg,Zf,S,-1,Wf,S,Tf,1,Vf,$f,[0,S,-1],V,bg,7,Of,1,S,R,S,R,fg,S,R,S,-2,Nf,S,R,O,U,1,S,R,1,S,Qf,Y,R],V,[-71,{},Mf,Y,S,-1,R,1,S,Y,Of,O,Y,R,uf,S,ig,1,Q,R,1,S,Y,O,[0,[0,O,
-2],[0,O,-2]],[0,Y,-2],25,kg,S,3,R,-1,1,R,S,2,R,Nf,S,Y,O,S,-1,1,S],V,[-11,{},Mf,S,Y,5,[0,Q,-3],S],V,[-12,{},Mf,S,R,O,-1,[0,O,-6,V,[0,S,Y,O]],df,Q,-1,S,[0,[0,Q,-3],V,[0,S,O]]]],1,[0,3,V,[0,V,[0,Q,-2]],R],3,qg,Y,-1,1,[-12,{},qg,Y,-1,[0,Y,2,Y,-1],Y,-1,S,3,[0,R,-2]],39,[0,[0,Q,-2,mf,-2],pg,-2,og,pg,-2,og,-5],49,[-3,{},[0,V,mg,[0,V,[0,S,V,[0,Q,O,V,[0,Q,O,-1,Q],R],V,[0,Q,O],R,-2]]],V,[0,Q,V,[0,Mf,[-10,{},Q,-2,X,[0,X,-2,O,-8,df,-5,wf,-1],uf,Q,-2],lg,O,-2,V,[0,Y,df]]]],[-3,{},[0,V,mg],V,[-6,{},V,ng,V,lg,
lf,of,mf]],48,[0,[0,V,ng,Ef],[0,O,X,-1,O,X]],49,Jf,599,[-1,{}],R,[0,O,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,S,-1,R],W,[0],W,[0],W,[0]],O,X],X],rg,V,sg]]);var zg=Af(Lf);function Ag(a){this.j=F(a,void 0,void 0,2048)}p(Ag,I);var Bg=[1,4];function Cg(a){this.j=F(a,11,void 0,2048)}p(Cg,I);var Dg=[0,Q,tf,Y];var Eg=[-11,{},[0,V,[0,Y,1,Y],uf,Df,U,V,[0,S,Y,O,Y],1,Y,-1,R],[0,S,-3,O,[0,Q,S],uf,-1],[0,Bg,ef,[0,Y],[0,2,Y],vf,[0,R,-1],O,Y,-2],[0,1,O,V,[0,S,-1],uf,tg,Q],Qf,[-1,{}],[0,[1,3],W,[0,[3,4],V,Kf,-1,nf,qf,V,Kf],S,rf],[0,[1,2,3,4,5,6,7,8,9,10,11],vf,-10],[0,[1,2],[3,4,5],W,Dg,W,rg,W,Dg,W,rg,W,[0,P]],[0,[1],W,rg,V,sg,Dg]];var Fg=[-3,{},S,Eg];function Gg(a){this.j=F(a,void 0,void 0,2048)}p(Gg,I);function Hg(a){this.j=F(a,5,void 0,2048)}p(Hg,I);function Ig(a){this.j=F(a,void 0,void 0,2048)}p(Ig,I);var Jg=[2,3,4];var Kg=[0,S,-2];var Lg=[0,[3,4],S,-1,hf,cf,Q,-1,S,-1];var Mg=[0,Jg,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,S,-1,Eg,V,[0,[4,5],Q,S,-1,vf,rf,S,Eg,Y],S,-1,ug,R,90,rf,W,[0,S,Y,[0,Y,O,Y]],W,[0,S],W,[0,S,Q],W,[0,S,Y],W,[0,S,-1],W,[0,S,Y],W,Lg,W,[0,1,S],W,Kg,W,[0,U,Y],W,[0,[5,6,7],Q,-2,S,vf,-1,nf],W,[0,[5,6],Q,-3,vf,nf],W,[0,[1,2],[4,5,6],W,Lg,W,Kg,S,vf,-1,nf],W,[0,[3,4],[8,9,10],Q,-1,nf,rf,Q,Y,S,vf,-1,nf],W,[0,S,U,S],W,[0,[4,5,6],Lg,S,1,vf,-1,nf],W,[0,S,-3,Q,S,-2],W,[0,S,Y],W,[0,V,[0,S,-1],S,
R],W,[0,S,-1]],Eg,V,[0,Q,-1,Eg],R],W,Fg,W,[0,[1,2],W,Dg,W,[0,S]]];var Ng=[0,Pe,yf,Pe,xf,Pe,zf];function Og(a){this.j=F(a,4,void 0,2048)}p(Og,I);var Pg=[-4,{},V,Mg,Eg,Ng];function Qg(a){this.j=F(a,3,void 0,2048)}p(Qg,I);var Rg=Af([-3,{},V,xg,Pg]);function Sg(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.S={};this.P={};this.C={};this.R={};this.B={};this.Y=new TextEncoder;this.V="";this.H=null;this.M=0;this.N=[];this.G=this.u=this.D=this.l=!1;this.v=[];this.O=[];this.A=[];this.i=a;this.F=this.i.createGain()}aa=Sg.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return r(c,loadWasmTtsBindings(),2);case 2:return b.g=c.h,r(c,Tg(b),3);case 3:return r(c,Ug(b),4);case 4:return c.return(Vg(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Wg(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Xg(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?(d.g=2,d=void 0):d=r(d,b.init(b.extensionId),2),d;if(d.g!=4)return r(d,Yg(b,a),4);(c=d.h)&&Zg(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function Yg(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=$g(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.g=4;break}g=f.value;ah(a,g);if(!g.remote||g.unloaded){k.g=3;break}h="/voices/"+g.fileId;k.i=5;return r(k,bh(a,h),7);case 7:d=!0;pa(k,3);break;case 5:qa(k);case 3:f=e.next();k.g=2;break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();ch(b);b.l=!1;b.D=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(dh(b);b.O.length>0;)window.clearTimeout(b.O.pop());b.v=[];b.N.length=0;b.H=null;b.M=0;d.g=0})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();dh(a);a.u=!0;return r(b,a.i.suspend(),2)}a.l=!1;b.g=0})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.l)return b.return();a.u=!1;return a.D?r(b,a.i.resume(),2):(a.A.length===0&&eh(a),b.return(fh(a)))}a.l=!0;gh(a);b.g=0})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,r(k,c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?r(k,c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.V===d){k.g=4;break}k.i=5;return r(k,hh(c,d,!1),7);case 7:e=c.C[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=ih(c,g);var n=ih(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);pa(k,4);break;case 5:return qa(k),k.return(Promise.reject(Error("Voice is not available")));case 4:c.V=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.g&&a.length){var z=new Hg,G=new Gg;var C=Pd(G,2,qd(a));var T=fe(z,[C]);var ph=new Ag,Nb=b.rate;var qh=Vd(ph,1,Bg,cd(!Nb||Nb<.1||Nb>10?1:Nb));var Rf=b.pitch;m=Pd(qh,6,cd(Rf?Math.pow(2,
(Rf-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.F.gain.value=Math.min(Math.max(b.volume,0),1));n=new Og;w=new Ig;z=T;z=de(z);Vd(w,2,Jg,z);z&&!Pc(z)&&Md(w.j);var rh=fe(n,[w]);var sh=new Cg;var th=ee(sh,3,m);var uh=ee(rh,2,th);var vh=new Qg;var wh=ee(vh,2,uh);var ed=Array.from(new Uint8Array(Rg(wh))),xh=c.R[x],yh=new Hf;var zh=Pd(yh,1,qd(xh));var fd=zg(zh),gd=c.g._malloc(ed.length);c.g.HEAPU8.set(ed,gd);var hd=c.g._malloc(fd.length);c.g.HEAPU8.set(fd,hd);var Ah=c.g._GoogleTtsInitBuffered(gd,hd,
ed.length,fd.length);c.g._free(gd);c.g._free(hd);if(!Ah)throw Error("Failed to initialize buffered synthesis.");eh(c)}}catch(Sf){return h=Sf instanceof Error?Sf.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.g=0}})};
function Vg(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.G&&b.data.type==="empty"&&(jh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.F.connect(a.i.destination)})}function ih(a,b){b=a.Y.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function eh(a){var b=setTimeout(function(){a.G=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)jh(a,{type:"error"}),ch(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)kh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=yg(c.slice(0,
e));d=d===0;e=c.j;ae(e,e[D]|0)!==void 0?lh(a,c,d):mh(a,null);d?ch(a):eh(a)}},0);a.A.push(b)}function ch(a){a.G=!1;a.g._GoogleTtsFinalizeBuffered()}function dh(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function kh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.l?c<-100||(c<2?jh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.l?jh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.O.push(c))):a.v.push(b))}
function gh(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())kh(a,c.value)}function lh(a,b,c){if(Gf(ce(b))===24E3){var d;b=(d=Ff(ce(b)))==null?void 0:new Uint8Array(Jb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});nh(a,d,c)}}
function nh(a,b,c){for(var d=a.H,e=a.M,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(mh(a,d),e=0,d=null)}e!==0&&(c?mh(a,d):(a.H=d,a.M=e))}function mh(a,b){b&&a.N.push(b);if(a.m)for(;b=a.N.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.D||a.u||fh(a)}function fh(a){return t(function(b){if(b.g==1)return a.m.connect(a.F),r(b,a.i.resume(),2);a.l=!0;a.D=!0;jh(a,{type:"start",charIndex:0});gh(a);b.g=0})}
function Wg(a,b){return t(function(c){return c.return(oh(a,b,!1))})}function Xg(a,b){return t(function(c){return c.return(oh(a,b,!0))})}function oh(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=$g(a,b),e=d.map(function(h){return hh(a,h.speakers[0].name,c)}),g.i=2,r(g,Promise.all(e),4);case 4:f="installed";c&&Zg(a);pa(g,3);break;case 2:qa(g),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function $g(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Bh(a,b,c){var d,e,f,g,h,k,m,n,w,x;return t(function(z){if(!a.B[b])return z.return(Promise.resolve());d=a.B[b];f=q(Object.entries(a.P));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,x=n,d===x){e=w;break}return e?z.return(hh(a,e,c)):z.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function hh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.i=2;return r(m,Bh(a,b,c),4);case 4:pa(m,3);break;case 2:return d=qa(m),m.return(Promise.reject(Error(""+d)));case 3:e=a.C[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.S[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Ch(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=ih(a,f),x=new Uint8Array(n),z=a.g._malloc(x.length);a.g.HEAPU8.set(x,z);n=a.g._GoogleTtsInstallVoice(w,z,n.byteLength);a.g._free(w);a.g._free(z);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,C){a.g.FS.syncfs(!1,function(T){T?C(T):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function jh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function Tg(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.i=2;return r(d,new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return pa(d,0);c=qa(d);throw c;})}
function Ug(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.i=2,r(e,fetch("voices.json"),4);case 4:b=e.h;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return r(e,b.json(),5);case 5:c=e.h;a.o=c;Zg(a);pa(e,0);break;case 2:throw d=qa(e),d;}})}
function Zg(a){a.S={};a.P={};a.C={};a.R={};a.B={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.P[f.name]=d.id;a.C[f.name]=d.fileId;a.R[f.name]=f.speaker;d.dependentVoiceId&&(a.B[f.name]=d.dependentVoiceId);ah(a,d);a.S[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function ah(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function bh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Ch(a,b,c){var d,e;return t(function(f){if(f.g==1)return r(f,Dh(c),2);d=f.h;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Dh(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?r(f,crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.h;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(Sg.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Eh=new Sg,Fh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Fh||(Fh=Eh.init(b.id));Fh.then(function(){switch(a.type){case "init":Eh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Eh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Eh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Eh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":Yg(Eh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Eh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Eh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Eh.onPause();c({result:"Paused speech"});break;case "resume":Eh.onResume(),c({result:"Resumed speech"})}});return!0});
